print(" ╔═══════════════════════════════╗")
print(" ║      HESAP MAKİNESİ           ║")
print(" ║═══════════════════════════════║")
print(" ║                               ║")
print(" ║ 1- TOPLAMA                    ║")
print(" ║ 2- ÇIKARMA                    ║")
print(" ║ 3- ÇARPMA                     ║")
print(" ║ 4- BOLME                      ║")
print(" ║ 5- TÜREV                      ║")
print(" ║ 6- İNTEGRAL                   ║")
print(" ╚═══════════════════════════════╝")
